# 處理 from_dir 裡的檔案與資料夾，並移動到 to_dir
from_dir: 'D:/workspace'
to_dir: 'D:/workspace/done'

# 可用的關鍵字 code, title, maker
name_format: "[{maker}_{code}] {title}"

# 是否只處理資料夾
only_dir: true

# 是否建立 dlsite 捷徑
create_shortcut: true
shortcut_filename: "dlsite"

# 是否下載封面
download_cover: true
cover_filename: "cover"

# 替換檔案名稱
replace_filename_patterns:
- from: ".wav.vtt"
  to: ".vtt"
- from: ".wav.srt"
  to: ".srt"
- from: ".flac.vtt"
  to: ".vtt"
- from: ".flac.srt"
  to: ".srt"
- from: ".mp3.vtt"
  to: ".vtt"
- from: ".mp3.srt"
  to: ".srt"
